# Generated by Django 2.1.2 on 2018-11-13 15:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20181029_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='badrooms',
            new_name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='batrooms',
        ),
        migrations.AddField(
            model_name='listing',
            name='bedrooms',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
